### PR TITLE
Implement nav menu that follows page structure.

### LINKED ISSUE #44: Header
Header needs to be working. links in header should point to right pages, structure of header should reflect structure of the site.

### PR DESCRIPTION
**Pull request by atelic**
In order for pages to show up in the nav bar, you **must** check the "Show in menus" box and give the page a "Page Title" in the Promote tab in admin.

Some images:

screen shot 2016-10-04 at 10 33 27 am
screen shot 2016-10-04 at 10 33 37 am

Hopefully closes #44

### CODE REVIEW

**Comment by 545zhou** [comment]
Hi @atelic  maybe you can check if this works with the newly added search icon and search bar?

**Comment by atelic** [comment]
Sure, how can I set up search to test it?

**Comment by 545zhou** [comment]
So pip install elasticsearch, version is 1.2.0. Then I guess it's all set.

**Comment by atelic** [comment]
Cool, this is looking and working great:

screen shot 2016-10-04 at 1 10 46 pm
screen shot 2016-10-04 at 1 10 51 pm

**Pull request merged**
