### PR TITLE
Add embedded youtube video and helper clear fix block

### PR DESCRIPTION
**Pull request by atelic**
No visual differences but these blocks decrease the amount of raw HTML that we have to use. It also means that the Jobs page can be 100% done with blocks now!!! 🎉  

Do not merge before #28

### CODE REVIEW

**Comment by atelic** [comment]
I'm a little concerned about how the migrations turned out here.

@HalcyonChimera @545zhou do you think one of you could try locally to see if they work?

**Comment by 545zhou** [comment]
The migration goes well and the youtube works on my local. But the job listing does not have the right width. Or do I need to add another block to wrap it?

**Comment by atelic** [comment]
Hmm, the width looks okay to me [here](http://cosio.herokuapp.com/get-involved/jobs/) which is now all implemented with the Jobs Listing. What are you seeing?

**Comment by 545zhou** [comment]
Interesting. If it works on heroku, I guess it's fine.

**Pull request merged**
